# Generated by Django 2.1 on 2018-08-20 15:02

from django.db import migrations, models
import django.db.models.deletion
import main.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_year', models.IntegerField(verbose_name='Год за который указан доход')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=main.models.make_doc_path, verbose_name='Файл')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Document', verbose_name='Декларация')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Полное название')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Office')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='document',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Office', verbose_name='Орган власти'),
        ),
    ]
